language: node_js
node_js:
  - "4"
  - "6"
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: npm@tabdigital.com.au
        api_key: $NPM_TOKEN
        on:
          tags: true
